#服务配置
server:
  port: 8086
#spring配置
spring:
  #1.应用配置
  application:
    name: ihrm-company #指定服务名
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/code_generator?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
  #3.JPA
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
